# Generated by Django 5.0.3 on 2024-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='practice')),
                ('icon', models.ImageField(upload_to='practice')),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
