# Generated by Django 5.1.2 on 2024-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_alter_lawlist_id_alter_lawyers_id_detaillaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=45)),
            ],
        ),
    ]
