# Generated by Django 5.1.2 on 2024-10-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0006_court'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255)),
                ('petitioner_name', models.CharField(max_length=255)),
                ('petitioner_phn', models.CharField(max_length=10)),
                ('petitioner_email', models.CharField(max_length=50)),
                ('petitioner_address', models.TextField()),
                ('case_date', models.DateField()),
                ('case_description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.court')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.courtdistrict')),
            ],
        ),
    ]
